openapi: 3.1.0

info:
  title: Examples
  version: 1.0.0

paths:
  /users:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                name:
                  type: string
                  example: John
                email:
                  type: string
                  example: john@email.com
                password:
                  type: string
                  example: '123456'
            examples:
              reference:
                $ref: '#/components/examples/CreateUserBody'
              literal:
                value:
                  name: John
                  email: john@email.com
                  password: '123456'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - email
                  - createdAt
                  - updatedAt
                properties:
                  id:
                    type: string
                    example: be8253f9-124b-4c32-b046-c25b6fd0af0c
                  name:
                    type: string
                    example: John
                  email:
                    type: string
                    example: john@email.com
                  createdAt:
                    type: string
                    example: '2024-01-01T00:00:00.000Z'
                  updatedAt:
                    type: string
                    example: '2024-01-01T00:00:00.000Z'
              examples:
                reference:
                  $ref: '#/components/examples/User'
                literal:
                  value:
                    id: be8253f9-124b-4c32-b046-c25b6fd0af0c
                    name: John
                    email: john@email.com
                    createdAt: '2024-01-01T00:00:00.000Z'
                    updatedAt: '2024-01-01T00:00:00.000Z'
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Invalid limit
              examples:
                reference:
                  $ref: '#/components/examples/Error'
                literal:
                  value:
                    message: Invalid limit

components:
  examples:
    CreateUserBody:
      description: Create user body
      value:
        name: John
        email: john@email.com
        password: '123456'
    User:
      description: User
      value:
        id: be8253f9-124b-4c32-b046-c25b6fd0af0c
        name: John
        email: john@email.com
        createdAt: '2024-01-01T00:00:00.000Z'
        updatedAt: '2024-01-01T00:00:00.000Z'
    Error:
      description: Error
      value:
        message: Invalid limit
